name: InnerSource repo crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '00 5 * * *'

jobs:
  build:
    name: InnerSource repo crawler
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run crawler tool
      uses: docker://ghcr.io/zkoppert/innersource-crawler:v1
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: innersource-portal-demo
        # for multiple topics, add them after a comma eg:
        # TOPIC: innersource,actions,security,python
        TOPIC: innersource

    - name: Push file to InnerSource Project Portal repository
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.INNERSOURCE_PORTAL_DEMO}}
      with:
        source_file: 'repos.json'
        destination_repo: 'innersource-portal-demo/project-portal-for-innersource'
        destination_branch: main
        user_email: 'zkoppert@github.com'
        user_name: 'Zachery Koppert'
